# Site settings
title: "...of the increase of his government and peace there shall be no end..." - Isa. 9:7
email: ebisong@ekababisong.org
description: Learning Systems, Machine Learning, Deep Neural Networks, Deep Reinforcement Learning
baseurl: ""
url: "https://ekababisong.org/"
#twitter_username: 
github_username:  dvdbisong
author: Ekaba Bisong

# social
social:
  name: Ekaba Bisong
  links:
    - https://www.linkedin.com/in/ekababisong/
    - https://plus.google.com/u/0/+EkabaBisong
    - https://github.com/dvdbisong
    - https://stackoverflow.com/users/3353760/ekaba-bisong?tab=profile

# Google Analytics
google_analytics: UA-89464100-1

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap